#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

apt install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start