#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
pt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Tolulope05 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include server_name_;/include server_name_;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/sites-enabled/default
service nginx restart
