#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install -y haproxy
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
sudo rm /etc/haproxy/haproxy.cfg
echo "
global
   log /dev/log    local0
   log /dev/log    local1 notice
   chroot /var/lib/haproxy
   stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
   stats timeout 30s
   user haproxy
   group haproxy
   daemon

defaults
   log global
   mode http
   option httplog
   option dontlognull
   timeout http-keep-alive 30000
   timeout connect 5000
   timeout client  50000
   timeout server  50000

frontend alx-frontend
   bind *:80
   default_backend alx-backend

backend alx-backend
   balance roundrobin
   server 17272-web-01 3.83.238.41:80 check
   server 17272-web-02 54.237.60.227:80 check

" >> /etc/haproxy/haproxy.cfg

service haproxy start
